/* Public HER Bible reader. Shared posting is intentionally held for secure member accounts + moderation. */
const bibleBooks = [
  ['Genesis',50],['Exodus',40],['Leviticus',27],['Numbers',36],['Deuteronomy',34],['Joshua',24],['Judges',21],['Ruth',4],['1 Samuel',31],['2 Samuel',24],['1 Kings',22],['2 Kings',25],['1 Chronicles',29],['2 Chronicles',36],['Ezra',10],['Nehemiah',13],['Esther',10],['Job',42],['Psalms',150],['Proverbs',31],['Ecclesiastes',12],['Song of Solomon',8],['Isaiah',66],['Jeremiah',52],['Lamentations',5],['Ezekiel',48],['Daniel',12],['Hosea',14],['Joel',3],['Amos',9],['Obadiah',1],['Jonah',4],['Micah',7],['Nahum',3],['Habakkuk',3],['Zephaniah',3],['Haggai',2],['Zechariah',14],['Malachi',4],['Matthew',28],['Mark',16],['Luke',24],['John',21],['Acts',28],['Romans',16],['1 Corinthians',16],['2 Corinthians',13],['Galatians',6],['Ephesians',6],['Philippians',4],['Colossians',4],['1 Thessalonians',5],['2 Thessalonians',3],['1 Timothy',6],['2 Timothy',4],['Titus',3],['Philemon',1],['Hebrews',13],['James',5],['1 Peter',5],['2 Peter',3],['1 John',5],['2 John',1],['3 John',1],['Jude',1],['Revelation',22]
];
const bibleTopics={Identity:['Psalm 139',14,'You are fearfully and wonderfully made.'],Confidence:['Proverbs 31',25,'Strength and dignity are part of your story.'],Peace:['Philippians 4',6,'Bring your worries to God, sister.'],Purpose:['Jeremiah 29',11,'God sees a future full of hope.'],Friendship:['Ecclesiastes 4',9,'Two are better than one.']};
const bibleBook=$('#bibleBook'), bibleChapter=$('#bibleChapter');
let currentBook='John',currentChapter=1;
function fillBooks(){bibleBook.innerHTML=bibleBooks.map(([book])=>`<option value="${book}"${book===currentBook?' selected':''}>${book}</option>`).join('');fillChapters();}
function fillChapters(){const match=bibleBooks.find(([book])=>book===currentBook),count=match?match[1]:1;if(currentChapter>count)currentChapter=1;bibleChapter.innerHTML=Array.from({length:count},(_,i)=>`<option value="${i+1}"${i+1===currentChapter?' selected':''}>Chapter ${i+1}</option>`).join('');}
function updateConversation(){const ref=`${currentBook} ${currentChapter}`;$('#conversationReference').textContent=ref;$('#conversationPrompt').textContent=`What did ${ref} reveal to you today? Share one truth you want to carry into your week.`;}
async function loadBibleChapter(){
  const reference=`${currentBook} ${currentChapter}`;$('#scriptureReference').textContent=reference;$('#scriptureText').innerHTML='<p class="scripture-loading">Opening the Word…</p>';updateConversation();
  try{const response=await fetch(`https://bible-api.com/${encodeURIComponent(reference)}?translation=web`);if(!response.ok)throw new Error('Bible service unavailable');const data=await response.json();if(!data.verses?.length)throw new Error('No verses found');$('#scriptureReference').textContent=data.reference;$('#scriptureText').innerHTML=`<div class="scripture-body">${data.verses.map(v=>`<p><sup>${v.verse}</sup>${v.text.trim()}</p>`).join('')}</div>`;}catch(error){$('#scriptureText').innerHTML='<p class="scripture-error">This chapter could not load right now. Please try again in a moment, sister.</p>';}
}
function changeChapter(direction){const index=bibleBooks.findIndex(([book])=>book===currentBook),limit=bibleBooks[index][1];currentChapter+=direction;if(currentChapter<1&&index>0){currentBook=bibleBooks[index-1][0];currentChapter=bibleBooks[index-1][1];}else if(currentChapter>limit&&index<bibleBooks.length-1){currentBook=bibleBooks[index+1][0];currentChapter=1;}else if(currentChapter<1||currentChapter>limit)return;fillBooks();loadBibleChapter();}
bibleBook.addEventListener('change',()=>{currentBook=bibleBook.value;currentChapter=1;fillChapters();});bibleChapter.addEventListener('change',()=>currentChapter=Number(bibleChapter.value));$('#loadChapter').addEventListener('click',loadBibleChapter);$('#previousChapter').addEventListener('click',()=>changeChapter(-1));$('#nextChapter').addEventListener('click',()=>changeChapter(1));
$$('[data-bible-topic]').forEach(button=>button.addEventListener('click',()=>{const [reference,chapter]=bibleTopics[button.dataset.bibleTopic];const space=reference.lastIndexOf(' ');currentBook=reference.slice(0,space);currentChapter=chapter;fillBooks();loadBibleChapter();}));
$('#saveChapter').addEventListener('click',()=>{const saved=JSON.parse(localStorage.getItem('pgwsSavedChapters')||'[]'),reference=`${currentBook} ${currentChapter}`;if(!saved.includes(reference))saved.push(reference);localStorage.setItem('pgwsSavedChapters',JSON.stringify(saved));$('#saveChapter').textContent='✓ Saved in this browser';});
function communityMessage(kind){if(window.pgwsOpenCommunityModal){window.pgwsOpenCommunityModal(kind);return;}const messages={reflection:'The secure sister sign-in is loading. Please try again in a moment.',wall:'The secure sister sign-in is loading. Please try again in a moment.',photo:'The secure sister sign-in is loading. Please try again in a moment.'};alert(messages[kind]);}
$('#openReflection').addEventListener('click',()=>communityMessage('reflection'));$('#openWallPost').addEventListener('click',()=>communityMessage('wall'));$('#openPhotoShare').addEventListener('click',()=>communityMessage('photo'));
fillBooks();loadBibleChapter();
