begin;

create table if not exists public.pgws_private_journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  study_day smallint not null check (study_day between 1 and 45),
  ciphertext text not null,
  iv text not null,
  salt text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pgws_private_journal_user_day_key unique (user_id, study_day)
);

comment on table public.pgws_private_journal_entries is
  'Client-encrypted PGWS journal pages. No plaintext reflection content is stored.';
comment on column public.pgws_private_journal_entries.ciphertext is
  'AES-GCM ciphertext created in the member browser before upload.';
comment on column public.pgws_private_journal_entries.salt is
  'Random PBKDF2 salt; the member journal lock phrase is never stored.';

create index if not exists pgws_private_journal_entries_user_id_idx
  on public.pgws_private_journal_entries (user_id);

alter table public.pgws_private_journal_entries enable row level security;
alter table public.pgws_private_journal_entries force row level security;

revoke all on table public.pgws_private_journal_entries from anon;
revoke all on sequence public.pgws_private_journal_entries_id_seq from anon;
grant select, insert, update, delete on table public.pgws_private_journal_entries to authenticated;
grant usage, select on sequence public.pgws_private_journal_entries_id_seq to authenticated;

drop policy if exists "Members read only their encrypted journal" on public.pgws_private_journal_entries;
create policy "Members read only their encrypted journal"
  on public.pgws_private_journal_entries
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Members create only their encrypted journal" on public.pgws_private_journal_entries;
create policy "Members create only their encrypted journal"
  on public.pgws_private_journal_entries
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Members update only their encrypted journal" on public.pgws_private_journal_entries;
create policy "Members update only their encrypted journal"
  on public.pgws_private_journal_entries
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Members delete only their encrypted journal" on public.pgws_private_journal_entries;
create policy "Members delete only their encrypted journal"
  on public.pgws_private_journal_entries
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

commit;
